
server:
  port: 8001

tim:
  tcpPort: 8000
  tcpEnabled: true
  webSocketPort: 18000
  webSocketEnabled: true
  bossThreadSize: 1
  workThreadSize: 8
  brokerId: 1000
  heartBeatTime: 3000 #心跳超时时间 单位毫秒
  logicUrl: http://127.0.0.1:8070/v1
  loginModel: 3
  #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  #  *                            4 允许所有端多设备登录 不踢任何设备


redisson:
  address: redis://127.0.0.1:6379
  password:
  timeout: 3000
  database: 0
  connectionPoolSize: 4
  connectionMinimumIdleSize: 4
  poolMinIdle: 8 #最小空闲数
  poolConnTimeout: 3000 # 连接超时时间(毫秒)
  poolSize: 10 # 连接池大小




spring:
  application:
    name: timTcpApplication
  profiles:
    active: '@profiles.active@'
  main:
    allow-circular-references: true

  redis:
    # 地址
    host: localhost
    # 端口，默认为6379  9736
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false




  rabbitmq:
    host: 10.209.248.224
    port: 5672
    addresses: 10.209.248.224
    username: root
    password: root
    virtual-host: my_vhost
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0


--- # nacos
spring:
  cloud:
    nacos:
      # nacos
      server-addr: '@nacos.server@'
      discovery:
        group: '@nacos.discovery.group@'
        namespace: ${spring.profiles.active}
      config:
        group: '@nacos.config.group@'
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml